### ISSUE TITLE
POMI - Refactor entity synthesis

### ISSUE THREAD

**Issue by gsanchezgavier** [newrelic/newrelic-coreint#108]
Replace current entity definitions files for a synthesis config similar with the defined [here](https://github.com/newrelic-experimental/entity-synthesis-definitions#synthesis):
example
```yaml
standalone: false
targets: ...
entity_synthesis_rules:
  - type: RAVENDB
    identifier: targetName
    name: targetName
    conditions:
    - attribute: metricName
      prefix: ravendb_
    tags:
      clusterName:
      targetName:
```
Create an Synthetiser based on this rules to replace the [current logic](https://github.com/newrelic/nri-prometheus/blob/main/internal/integration/spec.go)
