### ISSUE TITLE
Generator - Add mapping for POMI ignore or except configuration

### ISSUE THREAD

**Issue by gsanchezgavier** [newrelic/newrelic-coreint#112]
Make the non-service metrics like go_ and process_ configurable from the generator config to allow the customer to opt-out them.

Embed the [ignore/except metrics](https://docs.newrelic.com/docs/integrations/prometheus-integrations/install-configure-openmetrics/ignore-or-include-prometheus-metrics/): rule of pomi inside the exporter configuration so this metrics can be filtered. 

```yaml
integrations:
    - name: nri-ravendb
      config:
        ravendb_url: http://ravendb:8080
        exporter_port: 9440
        ignore_metrics:
          - prefixes:
            - "go_"
            - "process_"

```

**Comment by paologallinaharbur** [comment]
We are going to implement the config as follow:
```
transformations:
  - ignore_metrics:
      - prefixes:
          - kube_daemonset_
  - ignore_metrics:
      - prefixes:
          - kube_daemonset_
```

In these way we follow nri-prometheus notation and structure
