### ISSUE TITLE
Implement validations and assertions against the NR backend (Spec files)

### ISSUE THREAD

**Issue by ivancorrales** [newrelic/newrelic-coreint#157]
```
Example:

tests:
      nrqls:
        - query: "SELECT average(random_value) FROM Metrics WHERE average(random_value) > 44"
      entities:
        - type: "POWERDNS_AUTHORITATIVE"
          data_type: "Metric"
          metric_name: "powerdns_authoritative_up"
        - type: "POWERDNS_RECURSOR"
          data_type: "Metric"
          metric_name: "powerdns_recursor_up"
      metrics:
        - source: ""
          except: [ ]
          additionals: ""
```
