### ISSUE TITLE
Change how `lowDataMode` value is inherited

### ISSUE THREAD

**Issue by kang-makes** [newrelic/newrelic-coreint#230]
Right now helm-charts are using a `.Values.global.lowDataMode` before `.Values.lowDataMode` making impossible to override a `lowDataMode` set globally.

Related: https://github.com/newrelic/helm-charts/issues/553

**Comment by kang-makes** [comment]
The problem with this issue is how to put down the low data mode in a single chart inside the Helm Chart:

Given this template:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: example
data:
  lowDataMode-local:                 {{ .Values.lowDataMode        | default "default" }}
  lowDataMode-global:                {{ .Values.global.lowDataMode | default "default" }}
  lowDataMode-local-empty:           {{ empty .Values.lowDataMode        }}
  lowDataMode-global-empty:          {{ empty .Values.global.lowDataMode }}
  lowDataMode-local-toString:        {{ toString .Values.lowDataMode        }}
  lowDataMode-global-toString:       {{ toString .Values.global.lowDataMode }}
  lowDataMode-local-toString-empty:  {{ toString .Values.lowDataMode        | empty }}
  lowDataMode-global-toString-empty: {{ toString .Values.global.lowDataMode | empty }}
  lowDataMode-result:                {{ (include "newrelic-logging.lowDataMode" .) }}
```

if we put this in the `values.yaml` which means that we want low data mode to all pieces of the `nri-bundle` except the one we are configuring:
```yaml
global:
  lowDataMode: true
lowDataMode: false
```

it will template like this:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: example
data:
  lowDataMode-local:                 default
  lowDataMode-global:                true
  lowDataMode-local-empty:           true
  lowDataMode-global-empty:          false
  lowDataMode-local-toString:        false
  lowDataMode-global-toString:       true
  lowDataMode-local-toString-empty:  false
  lowDataMode-global-toString-empty: false
  lowDataMode-result:                true
```

So we can use neither `default` nor `empty` to look for empty variables.

This is going to take a bit of extra time, extra explanations and commenting to explain the "helm-pipeline-fu" we need for this.
