### ISSUE TITLE
S3 publish pipelines

### ISSUE THREAD

**Issue by roobre** [newrelic/newrelic-coreint#4]
### Goal

Integrate S3 publish action into all our different integrations

### Also in scope

We can take this opportunity to, in the same pr:

- Test built packages with [pkg test action](https://github.com/newrelic/integrations-pkg-test-action/) if not present [Sample PR](https://github.com/newrelic/nri-redis/pull/103/files):
```yaml
- name: Test packages installation
  uses: newrelic/integrations-pkg-test-action/linux@v1
  with:
    tag: ${{ env.TAG }}
    integration: 'nri-${{ env.INTEGRATION }}'
```
- After publishing, test packages uploaded to staging with [pkg test action](https://github.com/newrelic/integrations-pkg-test-action/).
```yaml
- name: Test staging repo
  uses: newrelic/integrations-pkg-test-action/linux@v1
  with:
    tag: ${{ env.TAG }}
    integration: 'nri-${{ env.INTEGRATION }}'
    stagingRepo: true
    packageLocation: repo
    upgrade: false
```
- After publishing, test packages uploaded to prod with [pkg test action](https://github.com/newrelic/integrations-pkg-test-action/)
```yaml
- name: Test staging repo
  uses: newrelic/integrations-pkg-test-action/linux@v1
  with:
    tag: ${{ env.TAG }}
    integration: 'nri-${{ env.INTEGRATION }}' # Required, with nri- prefix
    packageLocation: repo
    upgrade: false
```
- Fix snyk failure while using `latest` image
  - By adding `-e GO111MODULE=auto` to the docker run comand
- Allow push_pr pipelines to run on external PRs by [conditioning docker login](https://github.com/newrelic/nri-vsphere/pull/88)
