### ISSUE TITLE
Create nri-ravendb integration mock

### ISSUE THREAD

**Issue by davidbrota** [newrelic/newrelic-coreint#46]
For instance, create a bash script to mock the integration. 
Config file /etc/infra-agent/integrations.d/nri-ravendb-config.yaml

```
integrations:
  - name: nri-ravendb
    interval: 15s
    config:
      scrape_interval: 15s
      ravendb_url: http://live-test.ravendb.net
      exporter_port: 9441
```
bash script path: /var/db/newrelic-infra/newrelic-integrations/bin/nri-ravendb

take the envvars scrape_interval, ravendb_url and exporter_port to output a valid JSON Configuration Protocol (the payload must be in a single line)
```
{
  "config_protocol_version": "1",
  "action": "register_config",
  "config_name": "myconfig",
  "config": {
    "variables": {},
    "integrations": [
      {
        "name": "nri-prometheus",
        "interval": ${scrape_interval},
        "config": {
          "standalone": false,
          "targets": [
            {
              "description": "ravendb",
              "urls": [
                "http://localhost:${exporter_port}"
              ]
            }
          ]
        }
      },
      {
        "name": "prometheus-ravendb",
        "exec": "/usr/local/prometheus-exporters/ravendb_exporter",
        "timeout": 0,
        "env": {
          "RAVENDB_URL": ${ravendb_url},
          "PORT": ${exporter_port}
        }
      }
    ]
  }
}
```
upload both the config and the bash script somewhere in source.datanerd.us/coreint

Modify the [high-load-integration cli tool](https://source.datanerd.us/ohai/high-load-integration) in order to create payloads compatible with the config format.

**Comment by davidbrota** [comment]
For instance, create a bash script to mock the integration. 
Config file /etc/infra-agent/integrations.d/nri-ravendb-config.yaml

```
integrations:
  - name: nri-ravendb
    interval: 15s
    config:
      scrape_interval: 15s
      ravendb_url: http://live-test.ravendb.net
      exporter_port: 9441
```
bash script path: /var/db/newrelic-infra/newrelic-integrations/bin/nri-ravendb

take the envvars scrape_interval, ravendb_url and exporter_port to output a valid JSON Configuration Protocol (the payload must be in a single line)
```
{
  "config_protocol_version": "1",
  "action": "register_config",
  "config_name": "myconfig",
  "config": {
    "variables": {},
    "integrations": [
      {
        "name": "nri-prometheus",
        "interval": ${scrape_interval},
        "config": {
          "standalone": false,
          "targets": [
            {
              "description": "ravendb",
              "urls": [
                "http://localhost:${exporter_port}"
              ]
            }
          ]
        }
      },
      {
        "name": "prometheus-ravendb",
        "exec": "/usr/local/prometheus-exporters/ravendb_exporter",
        "timeout": 0,
        "env": {
          "RAVENDB_URL": ${ravendb_url},
          "PORT": ${exporter_port}
        }
      }
    ]
  }
}
```
upload both the config and the bash script somewhere in source.datanerd.us/coreint

Modify the high-load-integration cli tool in order to create payloads compatible with the config format.
